initial_pose: [1.1, -3.1, 4.1, -0.1, 0.1, 0.1]
frame_id: probe

# Strating point of the ultrasound image
x: 758
y: 90

# Size of the ultrasound image for visual servo
w: 527
h: 680

# Size of the ultrasound image for reconstruction
#1285-758   770-90
reconstruction_w: 527
reconstruction_h: 680

# Parameters of the ultrasound image for visual servo
servo_x: 820
servo_y: 150
servo_w: 150
servo_h: 150
spacing: 0.0872865 # 46.0/527.0
volume_resol_reduction: 3
